### ISSUE TITLE
Network Graph Enhancements

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#175]
This story is to track small changes to the Network Graph Feature. These items were part of the original stories, but they were approved "as is" in order to close and release the feature. These are being tracked here for prioritization at a later time. 

#103
- New dashboard - The “no meetings yet” text should be displayed below “your conversations” and left aligned. 

#107
- Paragraph break on back of card. 

#100
- Text color should be the same on all nodes (white) as long as it meets a11y contrast requirements. 
- Graph nodes do not match the Riff color pallet, or story specifications.

#101
- Node text is not white.

**Comment by mlippert** [comment]
Re the #107 enhancement, the ChartCard which implements the info text, currently only supports a text string w/ no formatting which is why there is no paragraph break. Not that it can't be done, but it is more work than just fixing the text to be displayed, and may involve touching all other places that ChartCard is used (all the graphs and meeting mediator I believe).

**Comment by adonahue** [comment]
Thanks @mlippert - good to know.

**Comment by adonahue** [comment]
De-prioritizing and / or consolidating this list into other cards. Closing this one.
