### ISSUE TITLE
Meeting Mediator, a11y, info box

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#28]
As a user, I would like more information about what the MM does, and what it's telling me. I would like to be able to click an info icon and see an explanation of how it works. 

As a PM, I would like this design pattern to match the info boxes on the back of the metrics in the dashboard. 

Mockups, slides 2 and 3 here: https://drive.google.com/open?id=1T9AE35-FoCZjUbr9tZq2UGO9LJibAdkM

**Comment by adonahue** [comment]
@arizzitano - When I test this w. Vox / Chrome / PC, The MM box does not take focus, front or back, and the info / close control does not get read out on focus. I now Vox is not a great A11y tool - did you test any of this w. your better tools?

@ebporter Test whether this takes focus?

** Text correction **
- [ ] Typo on back of card (and update "click" language). The text on the back of the card should be replaced with the following:

The Meeting Mediator provides real-time feedback about the last five minutes of your conversation. Thick lines and proximity to the central node indicate conversational dominance. Hover over a node to see how much a person has spoken. The center node displays the number of exchanges between participants. A higher number represents a more energetic conversation.

**Comment by jaedoucette** [comment]
tab focus is missing from this, and needs to be added?

**Comment by juliariffgit** [comment]
We'll get a license for JAWS and then test. Beth to take this action.

**Comment by juliariffgit** [comment]
This estimate is JUST for the small text and tab changes. Not for testing. New card being created for testing.

**Comment by arizzitano** [comment]
Hi folks. When I implemented this, I tested it with VoiceOver, which is what I use to test all my code. I was able to shift focus to 1) the info box heading, 2) the info button, 3) the contents of the info box (when the info button is selected via keyboard). Here are some screenshots of VoiceOver focus on these elements:

![image](https://user-images.githubusercontent.com/491289/61151376-cf910600-a4b3-11e9-9041-cc6fae9ee820.png)

![image](https://user-images.githubusercontent.com/491289/61151420-e9cae400-a4b3-11e9-9c1d-4a61adec4655.png)

![image](https://user-images.githubusercontent.com/491289/61151459-fbac8700-a4b3-11e9-9775-edba3d97d591.png)

The one potential issue I can see here (via VoiceOver) is with the info box close button. To shift focus to this button, I have to navigate *backward* from the initial focus area (on the info box text area), which isn't especially intuitive. It's not severe or functionality-blocking, just mildly annoying. A potential solution could be to swap DOM order of these elements (so the text is first, close button second) and use CSS to keep the display order as-is.

As far as tab focus goes, @jaedoucette could you elaborate a bit on what went wrong for you? I didn't add tabindex to this widget since I found the crucial elements (heading and buttons) were still selectable/navigable without it via arrow keys. @adonahue is the desired functionality for the entire widget container to be tab-focusable? IMO, it's not necessary to do this from a conformance standpoint as long as the elements within it are still selectable, but it's up to you.

As far as screen readers go, VoiceOver for Mac and JAWS/NVDA for Windows are the best for testing. People with visual impairments almost always use these OS-level screen readers, because they work both inside and outside of the browser. ChromeVox is based on Google's own browser accessibility API, and frequently behaves differently than the OS-level screen readers. This is a good post about how it works under the hood: https://marcozehe.wordpress.com/2013/09/07/why-accessibility-apis-matter/

**Comment by adonahue** [comment]
Thanks very much for the clarification @arizzitano . It sounds like the "problems" I found are really just a result of me not being a very proficient a11y tester. Based on your description and screen shots, it looks like this meets a11y requirements, and I am going to mark as complete. 
@ebporter
