### ISSUE TITLE
SPIKE: Can we collect and process audio and video from skype using the MS bot framework

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#45]
As a PM, I would like to integrate Riff with external data sources, so that I can have access to data and provide added value back in the terms of Riff metrics.

**Story Acceptance Criteria**

- A written determination of the technical feasibility of:
- [ ] If audio and video can be collected from skype and delivered to the bot framework
- [ ] If the bot framework can pass the data to Riff to do metrics processing
- [ ] If the bot can receive metrics back from Riff and pass them upstream to the user of the original service (skype)
- If there are conditions or nuances for any of the above, additional explanation about what we would need to consider.

**Comment by juliariffgit** [comment]
We need to split this - but this story will have what's going into Sprint 3.

**Comment by ebporter** [comment]
Splitting this into two stories:
1) Determining how to get a stream of data from Skype via the Microsoft Bot Framework and putting together a rapid prototype.
2) Determining how to send a stream of data to a Skype session (i.e. the meeting mediator) via the Bot Framework, again in a rapid prototype.

We'll try to tackle the first of these in Sprint 3.

**Comment by jordanreedie** [comment]
The Node version of the microsoft bot framework sdk does not support the realtime a/v processing library, which is the one we need. We have to use .NET (C#) for this, which is annoying.

**Comment by jordanreedie** [comment]
Things are looking pretty grim here. All of the "documentation" that presumably used to exist for RealTimeMediaCalling just redirects to its github page (e.g. https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-real-time-media-concepts). The repository itself hasn't been updated since last October. It seems they removed the ability for real time media bots to participate in group calls (i.e. any call other than a 1:1 call with the bot itself) in 2017 with "plans to re-add it in the future". As far as I can tell this feature is still missing. Also, it doesn't support skype for business and has no plans to.

**Comment by jordanreedie** [comment]
Beth sent an email to a microsoft rep asking what the deal is with this
