### ISSUE TITLE
Network Graph, Data

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#49]
As a PM, I want to add a network graph to Riff, so that users have a way to see how much they interact with their teams, and people outside their teams. This metric represents the dual concepts of "engagement and exploration" as it refers to the positive behaviors associated with high-functioning teams. 

As a first step, I'd like to just see the data available, to help inform what's possible in terms of a visualization. A concept image is attached and should be used as a model for what we'd like to be able to visually represent. 

The data we've chosen to represent meaningful connection between two parties are: Replies (comments), Responses (emojis), direct messages, and mentions. Each of these should be counted as a "connection" between two individuals. 

** Story acceptance criteria: **
A spreadsheet that contains the totals of each contact type above, for each participant in the NEXT course, where each data point is in a separate table, with a fifth table that's an aggregate of the first four. And also those matrices that are bounded to the PLG and Capstone team members. 
On the course data, teams should be identified.

**Comment by adonahue** [comment]
![image.png](https://images.zenhubusercontent.com/5cbf1c836caba0089f532d44/24a4860b-92d4-4076-8422-b8634848aa8b)

**Comment by juliariffgit** [comment]
Love this idea! Since the course splits learners into 2 different team at different points, it would be a nice-to-have to be able to compare the 2 different teams' activity side-by-side, as well.

In addition, if this data could be role-aware, it would be amazing. Staff interaction (like a mentor or TA, which we may be able to tag somehow) might be different from peer-to-peer interaction and might be useful to see.

**Comment by brecriffs** [comment]
The first part of this task, the spreadsheet, seems pretty straightforward.

**Comment by brecriffs** [comment]
After doing some discovery and determining a path of least resistance, I have updated the estimate on this ticket to 3.

**Comment by brecriffs** [comment]
Note: In the aggregate table, a reply and direct message could technically refer to the same message resulting in a count of 2 for that message. Similarly, if that message included a mention to that user, that message could incur a count of 3. 

It's possible that not counting replies as a direct message is desirable, although it is technically still a direct message in my opinion.

**Comment by brecriffs** [comment]
Should have 1 more point worth of work on this task.

**Comment by adonahue** [comment]
@brecriffs - I don't totally follow what you're saying here, can you list the sequence of user contacts that results in this double counting? 

>> Note: In the aggregate table, a reply and direct message could technically refer to the same message resulting in a count of 2 for that message. Similarly, if that message included a mention to that user, that message could incur a count of 3.

>> It's possible that not counting replies as a direct message is desirable, although it is technically still a direct message in my opinion.

**Comment by brecriffs** [comment]
Amy sends a DM to Brec. Brec does an official 'reply' to that DM. That reply from Brec will show as 1 in the direct message table AND 1 in the replies table for the Brec to Amy cell in each. And as a result, in the aggregate table, that reply will count as 2, since it is summing the replies and direct messages. 

Sorry, I hope that is clearer!

-------
Yes, much clearer @brecriffs . @jaedoucette - what are your thoughts on how to weight that count. It doesn't fee like it should be a full "2", since it represents one action, but something about DM does feel more personal and more "connected". 
-------

@brecriffs @adonahue I think it depends on what we want to visualize. Here are some possible options:

- We could make the width of each end of a visualized connection correspond to the number of messages sent _from_ that person. This would show one-sided relationships visually. (an line that's the same width throughout in this case, but maybe 2 at one end and 1 at the other for a more 1-sided conversation)
- We could make the width of each connection proportionate to the _product_ of the number of messages sent by each person. This grows faster when information exchange is equally balanced, and slowest for one-sided relationships. (a 4 in this case)
- We could ignore the visualization of 1-sided relationships for now, and just display the sum of communications (a 2 in this case)

**Comment by brecriffs** [comment]
I have completed the spreadsheet for all of the participants. In the following Google Drive folder exists the original document that I was editing and manipulating the data with, and another final .xlsx output called 'Network Graph - Course Data.xlsx'.
https://drive.google.com/drive/u/1/folders/1E8k8KKVQeKvDTfMqiYwvRD3TBvl6CJD5

There are comments in cell A1 in each tab describing how to interpret the data.

**Comment by brecriffs** [comment]
@adonahue As part two for this card, am I correct in saying that you want the above graph, but for each team (plg and capstone)?

**Comment by brecriffs** [comment]
Waiting for feedback on the usability of the course-wide data, and whether or not I should proceed with the team specific data. 

If there aren't requirements to have this data in CSV format, it might make sense to move forward with pulling this data directly from the Mattermost API for use with the actual implementation of this graph.

**Comment by jaedoucette** [comment]
@brecriffs I will want CSV format eventually for some of the analytics, but I think there's no reason it needs to be in that format for visualization purposes.

**Comment by adonahue** [comment]
@brecriffs - given that you've moved on to grabbing live data - I think this story can be considered complete, yes?

**Comment by brecriffs** [comment]
@adonahue Yeah, agreed.
