### ISSUE TITLE
A11y, center ball count, and MM focus for EDU

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#59]
As a user, I would like my screen reader to report the turn count on the Meeting Mediator. 
As an EDU user, I would would like the MM data table to be a visible, focus-able region, so that I have an easier time navigating the data in the table w. my screen reader. 

This story has two pieces of work. 

- [ ] The turn count in the Meeting Mediator should read out the following text: 
Title: "Total Turns Taken"
Text: "The group has taken {turn count} turns between participants in the last five minutes." Where {turn count} is the current turn count value when the center ball is selected for readout. 

- [ ] An enhancement to the EDU code that makes the MM a focus-able table, which results in a better screen reading and navigation experience.

**Comment by adonahue** [comment]
This card is work that was originally in Meeting Mediator, a11y, add data tables #27.

**Comment by adonahue** [comment]
The center ball and node metadata was not navigable, or readable with Chrome / Vox, which is the screen reading software I have. I can't determine if this is working properly, with a higher quality screen reader. I also tested w. NVDA and could not focus on or navigate the MM.

@arizzitano - when you tested w voice over, were you able to tab to the center ball and have it read the turn count?

**Comment by arizzitano** [comment]
@adonahue the "turns taken" caption exists within the data table below the mediator, and I was able to read that out using VoiceOver (added in https://github.com/rifflearning/riff-rtc/pull/123).

I intentionally did not add tab or keyboard focus to the _visible_ mediator nodes and center ball, because that data is already available in the mediator data tables down below. I wouldn't recommend duplicating this data for screen reader users -- if the preferred functionality is to make the mediator nodes themselves focusable, the tables below would be repetitive and possibly confusing. As long as the data within the tooltips is available within the data table, visually impaired users have access to all the same data as sighted mouse users.

ChromeVox isn't a great screen reader, but NVDA works pretty well and is free. We also recently got our own copy of JAWS, so could do some testing there if it's helpful to you folks.

**Comment by adonahue** [comment]
Thanks very much for the clarification @arizzitano . It sounds like the "problems" I found are really just a result of me not being a very proficient a11y tester. Based on your comments, it looks like this meets a11y requirements, and I am going to mark as complete. 
@ebporter
